### PR TITLE
Fixed a couple of typos

### PR DESCRIPTION
**Pull request by opusforlife2**
That's it.

### CODE REVIEW

**Comment by cmorty** [comment]
@opusforlife2 : Sorry for the late merge. I only just noticed this PR.

**Comment by opusforlife2** [comment]
Nyo problemo.

**Comment by opusforlife2** [comment]
Hey @cmorty, sorry for the off-topic ping. Mind updating the Jitsi Meet package? It's almost a year out of date.

**Comment by cmorty** [comment]
@opusforlife2 : Sorry, I'm not using it anymore. ;) I switched to Linux 1,5 years ago. If you make a PR I'll merge it. ;) Or I can pass it (the project) on to you. ;)

**Comment by opusforlife2** [comment]
Ah, I don't have the needed knowledge, sadly. Since you are sure that you don't want to maintain it anymore, how about creating an RFM issue in https://github.com/chocolatey-community/chocolatey-package-requests/issues? It'll allow some other interested maintainer to adopt the package.

Let me know if you would like me to open an issue there instead.

**Comment by cmorty** [comment]
Hey, yea go ahead and thank you! :)

**Pull request merged**
